pipeline:
  play_by_play: []

  shifts: []

  roster:
    - label: score_nhlapi
      task_type: source
      task_name: load_score_source
      emplace: {}
    - label: extract_games
      task_type: transform
      task_name: unnest_games_and_get_url
      emplace: {}
    - label: load_plays
      task_type: request
      task_name: fetch_play_by_play
      emplace: 
        input: NHL_GAMES
    - label: process_roster
      task_type: transform
      task_name: process_roster
      emplace: 
        input: RAW_PLAY_BY_PLAY
    - label: save_roster_to_clickhouse
      task_type: sink
      task_name: to_clickhouse
      emplace:
        to_save: NHL_ROSTER
        model: roster
        table: roster


  scores_sample:
    - label: score_nhlapi
      task_type: source
      task_name: load_score_source
      emplace: {}
    - label: extract_games
      task_type: transform
      task_name: unnest_games_and_get_url
      emplace: {}
    - label: process_goals
      task_type: transform
      task_name: process_goals
      emplace: {}
    - label: process_scores
      task_type: transform
      task_name: process_scores
      emplace: {}
    - label: save_game_state
      task_type: sink
      task_name: save_json_file
      emplace: 
        to_save: NHL_GAMES
        filepath: raw_nhl_scores.json
    - label: save_game_state
      task_type: sink
      task_name: save_csv_file
      emplace: 
        to_save: GOALS_CLEAN
        filepath: clean_nhl_goals.csv
    - label: save_game_state
      task_type: sink
      task_name: save_csv_file
      emplace: 
        to_save: SCORE_CLEAN
        filepath: scoreboard.csv

source:
  load_score_source:
    max_threads: 1
    sources:
      - http: 
          url: "https://api-web.nhle.com/v1/score/2024-10-30"
          output: SCORE_RAW

request:
  fetch_play_by_play:
    max_threads: 8
    input: $input
    requests:
      - http_batch:
          method: GET
          content_type: application/json
          url_column: url
          output: RAW_PLAY_BY_PLAY

transform:
  unnest_games_and_get_url:
    input: SCORE_RAW
    output: NHL_GAMES
    steps:
      - unnest_list_of_struct: games
      - with_columns: 
          url: 
            format:
              template: "https://api-web.nhle.com/v1/gamecenter/{}/play-by-play"
              columns: [id]
      - drop: [ prevDate, nextDate, gameWeek, oddsPartners ]

  process_roster:
    input: $input
    output: NHL_ROSTER
    steps:
      - select:
          game_id: id 
          rosterSpots: rosterSpots
      - unnest_list_of_struct: rosterSpots
      - select:
          team_id: teamId
          player_id: playerId
          first_name: firstName.default
          last_name: lastName.default
          position: positionCode
          headshot: headshot
          game_id: game_id
          jersey_number: sweaterNumber
      - uniform_id_type:
          include: [team_id, player_id, game_id]
      - uniform_id_type:
          include: [jersey_number]
          into: uint8

  process_plays:
    input: $input
    output: CLEAN_PLAYS
    steps: []

  process_scores:
    input: NHL_GAMES
    output: SCORE_CLEAN
    steps:
      - select:
          date: currentDate
          away_sog: awayTeam.sog
          away_score: awayTeam.score
          away_team: awayTeam.abbrev
          away_id: awayTeam.id
          home_sog: homeTeam.sog
          home_score: homeTeam.score
          home_team: homeTeam.abbrev
          home_id: homeTeam.id
          game_id: id

  process_goals:
    input: NHL_GAMES
    output: GOALS_CLEAN
    steps:
      - select:
          goals: goals
          date: currentDate
          away_team: awayTeam.abbrev
          away_id: awayTeam.id
          home_team: homeTeam.abbrev
          home_id: homeTeam.id
          game_id: id
      - unnest_list_of_struct: goals
      - select:
          game_id: game_id
          period: period
          time_in_period: timeInPeriod
          player_id: playerId
          player_name: name.default
          team_abbrev: teamAbbrev
          away_score: awayScore
          away_team: away_team
          home_score: homeScore
          home_team: home_team
          goal_type: goalModifier
          date: date
          
model:
  roster:
    team_id: uint64
    player_id: uint64
    first_name: str
    last_name: str
    headshot: str
    game_id: uint64
    jersey_number: uint8
    position: str

sink:
  save_json_file: 
    input: $to_save
    max_threads: 1
    sinks:
      - json: 
          filepath: $filepath
          merge_type: replace

  save_csv_file: 
    input: $to_save
    max_threads: 1
    sinks:
      - csv: 
          filepath: $filepath
          merge_type: replace

  to_clickhouse:
    input: $to_save
    max_threads: 8
    sinks:
      - clickhouse:
          url: http://default:password@localhost:8123/
          table: $table
          merge_type: replace
          model: $model
