model:

  # mandatory_key:
  # optional_key?: value <-- parse similar to typescript
  state_province:
    id: uint64
    name: str
    code: str

  person:
    id:
      dtype: uint64
      constraints: [primary]
    full_name: str
    first_name: str
    last_name: str
    birthdate: date
    deathdate: date
    birth_city: str
    birth_country_code: str
    birth_state_province_code: str

  player:
    person_id:
      dtype: uint64
      constraints: [primary, foreign, indexed]
    nhl_player_id?: # some guys simply don't have id yet
      dtype: uint64
      constraints: [unique, indexed]
    shoots_catches:
      dtype: char
    positions: list[str]
  
  # draft:

    
  # coach:


  # manager:


  # agent:


  nickname:
    person_id: uint64
    nickname: str

