transform:

  cs_player_to_nhl_player_url:
    - map:
        nhl_url: 
          action: format
          args: [ "player_ids.NHL" ]
          kwargs: { template: "https://api-web.nhle.com/v1/player/{}/landing" }

  # Get fresh NHL data
  # example: https://api-web.nhle.com/v1/player/8476453/landing
  nhl_player_to_person:
    - map:
        id: csid # from the previous step
        first_name: firstName.default # handle subpaths
        last_name: lastName.default # handle subpaths
        full_name: 
          action: concat_str # str concat, default with space
          args: [ "firstName.default", "lastName.default" ] 
          kwargs: { "separator" : " " }
        birthdate: birthDate
        birth_city: birthCity.default
        birth_state_province_name: birthStateProvince.default
        birth_state_country_code: birthCountry.default
        # is_nhl: <-- literal sample
        #   action: lit
        #   kwargs: 
        #     value: true
        #     dtype: bool
    - join:
        right: STATE_PROVINCE #  << named df
        right_select: 
          birth_state_province_code: code
          birth_state_province_name: name
        left_on: birth_state_province_name
        right_on: birth_state_province_name
        how: left
    - drop:
        birth_state_province_name: True

  nhl_player_to_player:
    - mapping:
        person_id: csid # from the previous step
        player_id: playerId
        shoots_catches: shootsCatches
        positions: 
          action: to_list
          args: position
      