logger:
  default:
    level: trace
    output_path_prefix: ""

runner:
  default:
    logger: default
    run_method: sync_lazy

transform:

  player_ids_to_urls:
    - select:
        nhl_url: 
          action: format
          args:
            template: "https://api-web.nhle.com/v1/player/{}/landing"
            args: [ "id" ]

pipeline:

  puckdata:
    - label: load_puckdata
      task: load_csv
      args: 
        - filepath: "puckdata.csv"
          df_name: PUCKDATA
        - filepath: "team.csv"
          df_name: TEAM
        - filepath: "player.csv"
          df_name: PLAYER

    - label: collate_player_events
      task: transform
      args:
        name: enrich_player_event
        input: PUCKDATA
        save_df: EVENTS
    
    - label: save_events
      task: save_csv
      args:
        - filepath: "/home/trxe/projects/capport/output/example/puckevents.csv"
          df_name: EVENTS

  players:
    - label: load_player_ids
      task: load_csv
      args: 
        - filepath: "/home/trxe/projects/capport/config/example/nhl_player_ids.csv"
          df_name: PLAYER_IDS

    - label: nhl_urls
      task: transform
      args:
        name: player_ids_to_urls
        input: PLAYER_IDS
        save_df: NHL_URLS

    - label: load_full_data
      task: http_request
      args:
        format: json
        df_from: NHL_URLS
        url_column: nhl_url
        df_to: NHL_PLAYER_DATA


    