transform:

  enrich_player_event:
    - select:
        id: ENTITYID
        x: COORDSX
        y: COORDSY
        z: COORDSZ
        team: TEAM
      
    - join:
        join: TEAM
        right_select:
          teamcode: TEAMCODE
          teamname: TEAMNAME
        left_on: team
        right_on: teamcode
        how: left
    
    - join:
        join: PLAYER
        right_select:
          entityid: entityid
          firstname: firstname
          last_name: lastname
          age: age
        left_on: id
        right_on: entityid
        how: left
    
    - select:
        id: id
        x: x
        y: y
        z: z
        teamname: teamname
        age: age
        last_name: last_name