name: CI

on:
  push:
    branches:
      - main
      - "f/**"
      - "b/**"
      - "r/**"
      - "d/**" # TODO: Remove
    paths:
      - '**.rs'
      - '**.yml'

permissions:
  contents: read

jobs:
  test_core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgresql-version: ['16', '17']
    services:
      postgres:
        image: postgres:${{ matrix.postgresql-version }}
        env:
          POSTGRES_USER: defuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: data_db
        mysql root password: root
        mysql user: dev
        mysql password: root
    - name: Run core tests
      run: cargo test --verbose --package cp_core
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: cargo clippy --tests -- -Dclippy::all
