name: CI

on:
  push:
    branches:
      - main
      - "f/**"
      - "b/**"
      - "r/**"
      - "d/**" # TODO: Remove
    paths:
      - '**.rs'

permissions:
  contents: read


env:
  CARGO_TERM_COLOR: always
  MYSQL_DATABASE: data_db
  MYSQL_USER: root
  MYSQL_PASSWORD: rsecret

jobs:
  test_core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgresql-version: ['16', '17']
    services:
      postgres:
        image: postgres:${{ matrix.postgresql-version }}
        env:
          POSTGRES_USER: defuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }}

    - name: Run core tests
      run: cargo test --verbose --package cp_core
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: cargo clippy --tests -- -Dclippy::all
